import { connect } from 'react-redux';
import Header from '../components/Header';

import { setUserProfile, logout } from '../actions';

const mapStateToProps = state => ({
  userProfile: state.userProfile,
});

// -------- hello

const mapDispatchToProps = (dispatch) => {
  console.log('Register callback!');

  window.hello.init({
    facebook: '120884018612158',
  }, {
    redirect_uri: 'redirect.html',
  });

  console.log('mapdispatchtoprops');

  window.hello.on('auth.login', async (auth) => {
    console.log('logged in', auth);
    const thing = window.hello('facebook');
    const userInfo = await thing.api('/me');
    console.log('userinfo', userInfo);
    const socialToken = auth.authResponse.access_token;

    const userProfile = await postJson('/api/auth', {
      network: 'facebook',
      socialToken,
    });
    console.log('userProfile generated by server', userProfile);
    dispatch(setUserProfile(userProfile));
  });
  return {
    onLoginButtonClick: () => {
      window.hello('facebook').login();
    },
    onLogoutButtonClick: () => {
      window.hello.logout('facebook');
      dispatch(logout());
    },
  };
};

const postJson = async (url, objToPost) => {
  const serializedJson = JSON.stringify(objToPost);
  const headers = {
    Accept: 'application/json',
    'Content-Type': 'application/json',
  };
  const options = {
    headers,
    method: 'POST',
    body: serializedJson,
  };
  const readableStream = await fetch(url, options);
  const parsedResponseObject = await (readableStream).json();
  return parsedResponseObject;
};

export default connect(mapStateToProps, mapDispatchToProps)(Header);
