import { connect } from 'react-redux';
import Header from '../components/Header';

import { _hello } from '../actions';

const mapStateToProps = state => ({
  user: state.user,
});

// -------- hello

const mapDispatchToProps = dispatch => {
  console.log('Register callback!')

  window.hello.init({
    facebook: '120884018612158'
  }, {
    redirect_uri: 'redirect.html'
  });

  window.hello.on('auth.login', async (auth) => {
    console.log('logged in', auth);
    const userInfo = await window.hello('facebook').api('/me');
    const socialToken = auth.authResponse.access_token;

    const serverToken = await postJson('/api/auth', {
      network: 'facebook',
      socialToken: socialToken
    });
    console.log('token generated by server', serverToken);
    dispatch(_hello(serverToken));
  });
  return {
    onLoginButtonClick: () => {
      window.hello('facebook').login();
    },
  }
};

const postJson = async (url, objToPost) => {
  const serializedJson = JSON.stringify(objToPost);
  const headers = {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  };
  const options = {
    headers,
    method: 'POST',
    body: serializedJson
  };
  const readableStream = await fetch(url, options);
  const parsedResponseObject = await (readableStream).json();
  return parsedResponseObject;
}

export default connect(mapStateToProps, mapDispatchToProps)(Header);
